export const INHIBITORS_DESTROYED = 'Inhibitors destroyed'
export const TOWERS_DESTROYED = 'Towers destroyed'
export const TOTAL_GOLD = 'Total Gold'
export const HERALDS = 'Heralds'
export const BARONS = 'Barons'
export const DRAKES = 'Drakes'
